default: &default
  adapter: postgresql
  encoding: unicode
  database: picks_development

  host: <%= ENV.fetch("DATABASE_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "root") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default
  database: picks_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "picks_production") %>
