fixture_sync_worker:
  cron: "*/10 10-23 * * *"
  class: "FixtureSyncWorker"
  queue: default

league_fixtures_sync_overlord:
  cron: "5 * * * *"
  class: "LeagueFixturesSyncOverlord"
  queue: default
