test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

s3_public:
  service: S3
  access_key_id: <%= PicksConfig.aws_s3_access_key_id %>
  secret_access_key: <%= PicksConfig.aws_s3_secret_access_key %>
  region: <%= PicksConfig.aws_s3_region %>
  bucket: <%= PicksConfig.aws_s3_public_bucket %>

s3_private:
  service: S3
  access_key_id: <%= PicksConfig.aws_s3_access_key_id %>
  secret_access_key: <%= PicksConfig.aws_s3_secret_access_key %>
  region: <%= PicksConfig.aws_s3_region %>
  bucket: <%= PicksConfig.aws_s3_private_bucket %>
